### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [zalefin/lambda-blazinggit#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by zalefin** [comment]
Hey there! I've added a GPLv3 license with 9379e29b53d97f3bb5454d9aeb272367c06754f3
Thanks for taking interest!
